puts "The students of my cohort at Makers Academy"
puts "----------------"
puts "Matteo Manzo"
puts "Marcin Wal"
puts "Ptolemy Barnes"
puts "Luke Clewlow"
puts "Emily Sas"
puts "Charlie Walsh"
puts "Huy Lee"